---
openapi: 3.0.0
info:
  title: koffie_labs_api_challenge
  description: The API for the Koffie Labs Backend Coding challenge
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/NEERAJANKAM_1/koffie_labs_api_challenge/1.0.0
  description: Koffie Labs Backend API challenge
paths:
  /lookup:
    post:
      summary: look up a new vin
      operationId: lookup_vehicle_details
      requestBody:
        description: request body
        content:
          application/ json:
            schema:
              $ref: '#/components/schemas/VinNumberObject'
        required: true
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleObject'
        "400":
          description: bad request
          content:
            application/ json:
              schema:
                type: string
                description: error message
        "404":
          description: not found
          content:
            application/json:
              schema:
                type: string
                description: no vehicle found with the input vin number
  /remove:
    post:
      summary: remove vin details from the cache
      operationId: remove_vehicle_details_from_cache
      requestBody:
        description: request body
        content:
          application/ json:
            schema:
              $ref: '#/components/schemas/VinNumberObject'
        required: true
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleDeleteObject'
        "404":
          description: not found
          content:
            application/json:
              schema:
                type: string
                description: vin is not present in the cache
  /export:
    get:
      summary: export the SQLite cache as a parquet file
      operationId: export_cache
      responses:
        "200":
          description: ok
components:
  schemas:
    VehicleObject:
      type: object
      properties:
        input_vin:
          type: string
          description: VIN of the vehicle
        make:
          type: string
          description: make of the vehicle
        model:
          type: string
          description: model of the vehicle
        year:
          type: string
          description: year of the vehicle
        body_class:
          type: string
          description: description of the vehicle
        cached_result:
          type: boolean
          description: boolean value indicating whether the value is returned from the cache.
      description: ok
    VehicleDeleteObject:
      type: object
      properties:
        input_vin:
          type: string
          description: VIN of the vehicle
        cache_delete_success:
          type: boolean
          description: boolean value indicating whether the vehicle details corresponding to the vin has been deleted from the cache or not.
    VinNumberObject:
      type: string
      description: vin number of the vehicle
